import { describe, expect, it } from 'vitest';
import type { buildTileBoardCardFeedbackState } from './tileBoardCardFeedbackState';
import type { buildBoardFeedbackModelState } from './tileBoardFeedbackModelState';
import { buildBoardFeedbackSurfaceComposition } from './tileBoardFeedbackSurfaceComposition';

const formatLabel = (label: string, rows: readonly (string | null | undefined)[]) =>
    [label, ...rows.filter((row): row is string => Boolean(row))].join(': ');

describe('tileBoardFeedbackSurfaceComposition', () => {
    it('composes grouped card and board feedback state into final surface state', () => {
        const cardFeedbackState = {
            cardActionPrioritySummaryAction: 'cashout',
            cardActionPrioritySummaryBeatCount: 5,
            cardActionPrioritySummaryScreenCue: 'burst',
            cardActionPrioritySummaryTier: 'cashout',
            cardBeatMapSummaryAction: 'cashout',
            cardBeatMapSummaryBeatCount: 5,
            cardBeatMapSummaryMeterFill: 100,
            cardBeatMapSummaryScreenCue: 'burst',
            cardBeatMapSummaryTier: 'cashout',
            cardCadenceMapSummaryAction: 'cashout',
            cardCadenceMapSummaryBeatCount: 5,
            cardCadenceMapSummaryScreenCue: 'burst',
            cardCadenceMapSummaryTier: 'cashout',
            cardFeedbackActionCuesAttr: 'burst',
            cardFeedbackActionPriorityAttr: 'cash-now:2',
            cardFeedbackActionPriorityRows: [{ count: 2, id: 'cash-now', label: 'Cash now', role: 'Cashout', screenCue: 'burst', tone: 'cashout' }],
            cardFeedbackBeatActionMapAttr: 'cashout:hit now:2',
            cardFeedbackBeatCountsAttr: 'cashout:2',
            cardFeedbackBeatMapLabel: 'Beat map',
            cardFeedbackBeatRows: [{ action: 'hit now', beatCount: 5, count: 2, id: 'cashout', label: 'Cashout', screenCue: 'burst', tone: 'cashout' }],
            cardFeedbackBeatTiersAttr: 'cashout:2',
            cardFeedbackCadenceMapLabel: 'Cadence map',
            cardFeedbackCadenceRows: [{ action: 'cash now', beatCount: 5, count: 2, id: 'cashout', label: 'Cashout', screenCue: 'burst', tone: 'cashout' }],
            cardFeedbackCadencesAttr: 'cashout:cash now:2',
            cardFeedbackMarkerShapesAttr: 'linked-route',
            cardFeedbackPrimaryActionAttr: 'cash-now',
            cardFeedbackPrimaryCardCueAttr: 'burst',
            cardFeedbackRouteGlyphsAttr: '=>',
            cardFeedbackShotMapAttr: 'cash-now:2',
            cardFeedbackShotMapLabel: 'Shot map',
            cardFeedbackShotMapRows: [{ count: 2, detail: 'Two shots', id: 'cash-now', label: 'Cash now', role: 'Cashout', screenCue: 'burst', shotLabel: 'Cash', tone: 'cashout' }],
            cardFeedbackStatesAttr: 'hidden:2',
            cardFeedbackTraitComboSurgeActive: false,
            cardFeedbackTraitLaneActionsAttr: 'shard:cashout:1',
            cardFeedbackTraitLaneBeatMapLabel: 'Trait lane map',
            cardFeedbackTraitLaneBeatMapMeterFill: 50,
            cardFeedbackTraitLaneBeatRows: [{ action: 'cashout', beatCount: 4, count: 1, id: 'shard', label: 'Shard lane', role: 'Cashout' }],
            cardFeedbackTraitLaneBeatsAttr: 'shard:1',
            cardFeedbackTraitLaneCuesAttr: 'shard',
            cardFeedbackTraitLanePrimaryActionAttr: 'cashout',
            cardFeedbackTraitPayoffStackActive: false,
            cardFeedbackTraitRouteIntensitiesAttr: 'ready:1',
            cardFeedbackTraitRouteTiersAttr: 'route:1',
            cardFeedbackVisibleTraitPreviewCount: 1,
            cardShotMapSummaryAction: 'cashout',
            cardShotMapSummaryBeatCount: 5,
            cardShotMapSummaryScreenCue: 'burst',
            cardShotMapSummaryTier: 'cashout',
            primaryCardActionPriorityRow: { count: 2, id: 'cash-now', label: 'Cash now', role: 'Cashout', screenCue: 'burst', tone: 'cashout' },
            primaryCardFeedbackBeatRow: { action: 'hit now', beatCount: 5, count: 2, id: 'cashout', label: 'Cashout', screenCue: 'burst', tone: 'cashout' },
            primaryCardFeedbackCadenceRow: { action: 'cash now', beatCount: 5, count: 2, id: 'cashout', label: 'Cashout', screenCue: 'burst', tone: 'cashout' },
            primaryCardFeedbackShotAudioCue: 'card-shot-cashout',
            primaryCardFeedbackShotFocus: 'cashout',
            primaryCardFeedbackShotRow: { count: 2, detail: 'Two shots', id: 'cash-now', label: 'Cash now', role: 'Cashout', screenCue: 'burst', shotLabel: 'Cash', tone: 'cashout' },
            primaryCardFeedbackShotScreenCue: 'burst',
            primaryTraitLaneAudioCue: 'trait-lane-shard',
            primaryTraitLaneBeatRow: { action: 'cashout', beatCount: 4, count: 1, id: 'shard', label: 'Shard lane', role: 'Cashout' },
            primaryTraitLaneScreenCue: 'burst',
            traitLaneBeatMapSummaryAction: 'cashout',
            traitLaneBeatMapSummaryBeatCount: 4,
            traitLaneBeatMapSummaryScreenCue: 'burst',
            traitLaneBeatMapSummaryTier: 'cashout'
        } as const;

        const boardFeedbackModelState = {
            activePowerBoardChip: null,
            boardChainAccessibilitySummary: {
                followupCount: 1,
                label: 'Cash route ready',
                payoffStackCount: 0,
                primaryLine: 'Cash route ready',
                readyCount: 1,
                rewardHotCount: 1,
                secondaryLine: null,
                setupCount: 0,
                surgeCount: 0,
                tone: 'cashout'
            },
            boardChainCueMeterFill: 100,
            boardChainCueMeterState: 'cashout',
            boardChainMarkerKeyMeterFill: 60,
            boardChainMarkerKeyRows: [{ action: 'Route setup', count: 1, glyph: '=>', id: 'linked-route', label: 'Linked route', shape: 'linked-route' }],
            boardChainMarkerKeySummaryAction: 'route',
            boardChainMarkerKeySummaryBeatCount: 3,
            boardChainMarkerKeySummaryScreenCue: 'pulse',
            boardChainMarkerKeySummaryTier: 'ready',
            boardChainOpportunity: {
                arcadeCallout: null,
                armedPerkLabel: null,
                armedPerkPayoff: null,
                beatSignal: { action: 'Cash now', audioCue: 'cashout-beat', beatCount: 5, detail: 'Cash now', label: 'Cash route', screenCue: 'burst', tier: 'cashout' },
                chainReadyCount: 1,
                chainReadyTileCount: 2,
                chaseLabel: null,
                comboSurgeLabel: null,
                cue: 'Cash route',
                examples: ['Cash route'],
                lines: ['Cash route'],
                milestoneActionLabel: 'Cash route',
                milestoneBeatCount: 5,
                milestoneMeterFill: 100,
                milestoneScreenCue: 'burst',
                milestoneTargetLabel: '2 pairs',
                milestoneTier: 'cashout',
                milestoneTone: 'cashout',
                momentumLabel: null,
                nextActionDetail: 'Cash now',
                nextActionId: 'cashout',
                nextActionLabel: 'Cash now',
                nextActionTone: 'cashout',
                nextTarget: '2 pairs',
                priorityLabel: 'Best',
                rewardCue: 'Reward ready',
                rewardHot: true,
                rewardUrgencyLabel: 'Now',
                rewardUrgencyTier: 'next',
                selectedFollowupCount: 1,
                selectedFollowupLabel: '2 pairs',
                setupCount: 0,
                streakCashoutReady: true,
                targetPlanLabel: 'Cash route',
                tone: 'cashout'
            },
            boardChainOpportunityLabel: 'Chain surface',
            boardChainOpportunityMeterFill: 100,
            boardChainOpportunityNextActionMeterFill: 100,
            boardChainOpportunityNextActionTier: 'now',
            boardChainOpportunityNextActionVerb: 'Now',
            boardChainOpportunityPriorityId: 'best',
            boardChainRecipeChips: ['Cash'],
            boardChainRecipeRows: [{ action: 'Cash', label: 'Cash', laneId: 'score', recipe: 'Cash route', roleId: 'cashout', sourceLine: 'North lane' }],
            boardChainSequenceAccessibleLabel: 'Cash route sequence',
            boardChainSequenceCue: { first: 'Cash route', keep: 'Hold route', then: 'Reward', tone: 'cashout' },
            boardHazardOpportunity: { action: 'inspect', count: 0, detail: '', family: 'none', label: '', screenCue: 'tick', tier: 'watch', trigger: 'none', valueLabel: '' },
            boardOpportunityCompassRows: [{ action: 'Cash now', detail: 'Two pairs are primed', id: 'chain', impactCue: 'route cashout', label: 'Cash route', tone: 'chain', value: '2 pairs' }],
            boardPickupOpportunity: { count: 0, examples: [], sequenceCue: null, stackCue: null, stackDetail: null, target: 'none', tileCount: 0, valueLabel: '0 pickups' },
            boardRewardLadderState: { accessibleLabel: 'Reward ladder', actionAttr: 'cashout', attr: 'next', entries: [], focusId: null, lead: null, leadAccessibleLabel: undefined, summaryAction: 'cashout', summaryBeatCount: 5, summaryMeterFill: 100, summaryScreenCue: 'burst', summaryTier: 'cashout' },
            boardTraitInteractionLaneActionMapAttrValue: 'score:cashout',
            boardTraitInteractionLaneMap: [{ count: 1, cue: 'pulse', id: 'score', label: 'Score lane' }],
            boardTraitInteractionLaneMapAccessibleLabel: 'Trait lane map',
            boardTraitInteractionLaneMapAttrValue: 'score',
            boardTraitInteractionLaneMapMeterFill: 50,
            boardTraitInteractionLaneRoleMapAttrValue: 'cashout',
            boardTraitModeCue: null,
            boardTraitModeCueLabel: undefined,
            chainMarkerIntensity: { action: 'Match route', count: 1, id: 'ready', label: 'Ready' },
            focusedChainMarkerShape: 'linked-route',
            focusedPreviewChip: null,
            focusedPreviewChipLabel: undefined,
            primaryBoardTraitInteractionLane: { count: 1, cue: 'pulse', id: 'score', label: 'Score lane' },
            traitOpportunitySummary: { interactionLines: [], tiles: [{ label: 'Rune', traitKind: 'score' }] }
        } as const;

        const state = buildBoardFeedbackSurfaceComposition({
            boardFeedbackModelState: boardFeedbackModelState as ReturnType<typeof buildBoardFeedbackModelState>,
            cardFeedbackState: cardFeedbackState as ReturnType<typeof buildTileBoardCardFeedbackState>,
            deps: { formatLabel },
            lastResolutionFeedback: 'cashout',
            reduceMotion: false
        });

        expect(state.boardChainOpportunitySurfaceView.accessibleLabel).toBe('Chain surface');
        expect(state.boardStatusChipsView.pickupOpportunity).toBeNull();
        expect(state.cardFeedbackTelemetryAttrs['data-card-feedback-primary-action']).toBe('cash-now');
        expect(state.chainFeedbackTelemetryAttrs['data-chain-opportunity-beat-action-id']).toBe('cashout');
        expect(state.opportunityFeedbackTelemetryAttrs['data-opportunity-best-id']).toBe('chain');
    });
});
