import { expect, test, type Locator, type Page } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { openPlayablePathFixture } from './playablePathHelpers';
import { openChooseYourPath, startClassicRunFromModeSelect } from './visualScreenHelpers';

const captureRoot = process.env.VISUAL_CAPTURE_ROOT ?? path.join('docs', 'visual-capture');
const portfolioRoot = path.join(captureRoot, 'portfolio-smoke');

type Capture = {
  name: string;
  file: string;
  viewport: string;
};

const captures: Capture[] = [];

test.describe('portfolio visual smoke gate', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    await page.waitForLoadState('networkidle');
  });

  test.afterAll(async () => {
    await mkdir(portfolioRoot, { recursive: true });
    const lines = [
      '# Portfolio Visual Smoke Captures',
      '',
      'Fast reviewer-path captures generated by `yarn test:e2e:visual:smoke`.',
      '',
      '| Screen | Viewport | Artifact |',
      '| --- | --- | --- |',
      ...captures.map(
        (capture) =>
          `| ${capture.name} | ${capture.viewport} | [${capture.file}](./${capture.file}) |`,
      ),
      '',
    ];

    await writeFile(path.join(portfolioRoot, 'README.md'), lines.join('\n'), 'utf8');
  });

  test('captures the desktop reviewer path', async ({ page }) => {
    test.setTimeout(180_000);
    await page.setViewportSize({ width: 1440, height: 960 });

    const primaryCta = await findPrimaryCta(page);
    await expect(primaryCta, 'main menu primary CTA must be visible').toBeVisible();
    await assertReadableControl(primaryCta, 'main menu primary CTA');
    await capture(page, 'main-menu-desktop', 'Main menu');

    await startFeaturedRun(page);
    await capture(page, 'featured-run-start-desktop', 'Featured run start');

    await assertBoardVisible(page);
    await capture(page, 'active-board-desktop', 'Active board');

    await reachRelicOffer(page);
    await capture(page, 'relic-offer-desktop', 'Relic offer');

    await openPlayablePathFixture(page, 'activeRunWithHazards');
    await openSettings(page);
    await capture(page, 'settings-overlay-desktop', 'Settings overlay');
  });

  test('captures readable mobile critical controls', async ({ page }) => {
    test.setTimeout(90_000);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto('/');
    await page.waitForLoadState('networkidle');

    const primaryCta = await findPrimaryCta(page);
    await expect(primaryCta, 'mobile primary CTA must be visible').toBeVisible();
    await assertReadableControl(primaryCta, 'mobile primary CTA');

    const settings = settingsControl(page);
    await expect(settings, 'mobile settings control must be visible').toBeVisible();
    await assertReadableControl(settings, 'mobile settings control');

    await capture(page, 'mobile-main-menu', 'Mobile main menu');
  });
});

async function capture(page: Page, fileBase: string, name: string) {
  await mkdir(portfolioRoot, { recursive: true });
  const file = `${fileBase}.png`;
  await page.screenshot({ path: path.join(portfolioRoot, file), fullPage: true });
  const viewport = page.viewportSize();
  captures.push({
    name,
    file,
    viewport: viewport ? `${viewport.width}x${viewport.height}` : 'unknown',
  });
}

async function findPrimaryCta(page: Page) {
  const candidates = [
    page.getByRole('button', { name: /featured|start|begin|play|classic|practice/i }).first(),
    page.getByRole('link', { name: /featured|start|begin|play|classic|practice/i }).first(),
  ];

  return firstVisible(candidates, 'primary CTA');
}

async function startFeaturedRun(page: Page) {
  await openChooseYourPath(page);
  await startClassicRunFromModeSelect(page);
  await page.waitForLoadState('networkidle').catch(() => undefined);
}

async function assertBoardVisible(page: Page) {
  const board = page
    .locator(
      [
        '[data-testid*="board" i]',
        '[aria-label*="board" i]',
        'canvas',
        '.game-board',
        '.memory-board',
      ].join(', '),
    )
    .first();

  await expect(board, 'active board must render').toBeVisible({ timeout: 15_000 });

  const box = await board.boundingBox();
  expect(box?.width ?? 0, 'board width must be substantial').toBeGreaterThan(220);
  expect(box?.height ?? 0, 'board height must be substantial').toBeGreaterThan(180);

  const canvas = page.locator('canvas').first();
  if (await canvas.isVisible().catch(() => false)) {
    const hasContent = await canvas.evaluate((node) => {
      const source = node as HTMLCanvasElement;
      const context = source.getContext('2d');
      if (!context || source.width === 0 || source.height === 0) {
        return true;
      }

      const sampleWidth = Math.min(source.width, 96);
      const sampleHeight = Math.min(source.height, 96);
      const data = context.getImageData(0, 0, sampleWidth, sampleHeight).data;
      for (let index = 3; index < data.length; index += 4) {
        if (data[index] > 0) {
          return true;
        }
      }
      return false;
    });
    expect(hasContent, 'board canvas must not be blank').toBe(true);
  }
}

async function reachRelicOffer(page: Page) {
  await openPlayablePathFixture(page, 'relicDraft');
  await expect(relicOffer(page), 'relic offer must appear on the reviewer path').toBeVisible({
    timeout: 30_000,
  });
}

function relicOffer(page: Page) {
  return page
    .getByTestId('game-relic-offer-overlay')
    .or(page.getByRole('dialog', { name: /relic draft/i }))
    .first();
}

async function openSettings(page: Page) {
  const settings = settingsControl(page);
  await expect(settings, 'settings control must be visible').toBeVisible();
  await settings.click();

  await expect(
    page
      .locator('[role="dialog"], [data-testid*="settings" i], [aria-label*="settings" i]')
      .filter({ hasText: /settings|audio|motion|controls|display/i })
      .first(),
    'settings overlay must open',
  ).toBeVisible();
}

function settingsControl(page: Page) {
  return page
    .getByRole('button', { name: /settings|options|preferences/i })
    .or(page.getByLabel(/settings|options|preferences/i))
    .first();
}

async function firstVisible(candidates: Locator[], label: string) {
  for (const candidate of candidates) {
    if (await candidate.isVisible().catch(() => false)) {
      return candidate;
    }
  }

  await expect(candidates[0], `${label} must be visible`).toBeVisible();
  return candidates[0];
}

async function assertReadableControl(locator: Locator, label: string) {
  const box = await locator.boundingBox();
  expect(box?.width ?? 0, `${label} width must be readable`).toBeGreaterThanOrEqual(44);
  expect(box?.height ?? 0, `${label} height must be readable`).toBeGreaterThanOrEqual(32);

  const textMetrics = await locator.evaluate((node) => {
    const element = node as HTMLElement;
    return {
      clientWidth: element.clientWidth,
      scrollWidth: element.scrollWidth,
      clientHeight: element.clientHeight,
      scrollHeight: element.scrollHeight,
    };
  });

  expect(textMetrics.scrollWidth, `${label} text must fit horizontally`).toBeLessThanOrEqual(
    textMetrics.clientWidth + 2,
  );
  expect(textMetrics.scrollHeight, `${label} text must fit vertically`).toBeLessThanOrEqual(
    textMetrics.clientHeight + 2,
  );
}
