/**
 * Writes docs/REMOVED_DUNGEON_LAYER.md from the live catalogs, before they are deleted.
 *
 * The dungeon layer is being removed because it breaks the flow of the loop this game is actually
 * about. Removed content nobody wrote down is content nobody can weigh returning, so this reads
 * the definitions the game itself holds and prints every kind, effect, boss, hazard, archetype,
 * objective and route special with what it did - accurately, because it is generated from the
 * source rather than remembered.
 *
 * Run: yarn docs:dungeon-archive
 */
import fs from 'node:fs';
import path from 'node:path';
import {
    DUNGEON_CARD_EFFECT_DEFINITIONS,
    DUNGEON_CARD_EFFECT_ORDER,
    DUNGEON_CARD_KIND_DEFINITIONS,
    DUNGEON_CARD_KIND_ORDER
} from '../src/shared/dungeon-cards';
import { DUNGEON_BOSS_DEFINITIONS } from '../src/shared/dungeon-boss-rules';
import { calculateMemoryTaxReview, MEMORY_TAX_AXES } from '../src/shared/mechanic-feedback';
import { HAZARD_TILE_DEFINITIONS } from '../src/shared/hazard-tiles';

/*
 * The modules the removal deletes.
 *
 * This was a `readdirSync` glob over `src/shared/dungeon-*.ts`, with a comment claiming it was a
 * literal list "so the archive still names them accurately after they are gone". It was not, and
 * the first deletion proved it: `dungeon-tile-augmentation-rules.ts` went in Gen 172 and a re-run
 * would have quietly dropped it from the record. An archive that forgets what it archived is worse
 * than no archive, because it looks complete.
 *
 * So it is now the literal list the comment always described, captured from the glob on the last
 * commit where every one of these still existed. Anything added here has to be added by hand, which
 * is the correct amount of friction for a record of what was destroyed.
 */
const DELETED_MODULES: readonly string[] = [
    'src/shared/dungeon-blueprint-policy-rules.ts',
    'src/shared/dungeon-board-generation-rules.ts',
    'src/shared/dungeon-board-status.ts',
    'src/shared/dungeon-boss-clear-rules.ts',
    'src/shared/dungeon-boss-rules.ts',
    'src/shared/dungeon-card-read-model.ts',
    'src/shared/dungeon-card-recipe-rules.ts',
    'src/shared/dungeon-cards.ts',
    'src/shared/dungeon-combinatoric-matrix.ts',
    'src/shared/dungeon-e2e-fixtures.ts',
    'src/shared/dungeon-encounter-context-rules.ts',
    'src/shared/dungeon-enemy-card-rules.ts',
    'src/shared/dungeon-enemy-hazard-rules.ts',
    'src/shared/dungeon-exit-rules.ts',
    'src/shared/dungeon-floor-blueprint-rules.ts',
    'src/shared/dungeon-key-copy.ts',
    'src/shared/dungeon-key-rules.ts',
    'src/shared/dungeon-match-reward-rules.ts',
    'src/shared/dungeon-reveal-rules.ts',
    'src/shared/dungeon-room-rules.ts',
    'src/shared/dungeon-room-targeting-rules.ts',
    'src/shared/dungeon-rules.ts',
    'src/shared/dungeon-run-state-rules.ts',
    'src/shared/dungeon-save-migration.ts',
    'src/shared/dungeon-scout-rules.ts',
    'src/shared/dungeon-showcase-run-rules.ts',
    'src/shared/dungeon-tile-augmentation-rules.ts',
    'src/shared/dungeon-topology.ts',
    'src/shared/dungeon-trap-rules.ts',
    'src/shared/dungeon-versioning.ts'
];

const lines: string[] = [];
const push = (line = ''): void => {
    lines.push(line);
};
const cell = (value: unknown): string => String(value ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

push('# The dungeon layer, archived');
push();
push('> Generated by `yarn docs:dungeon-archive` from the catalogs themselves, on the commit before they were');
push('> deleted. Nothing here is remembered or paraphrased: every row is the definition the game shipped.');
push();
push('## Why it was removed');
push();
push('The dungeon layer put a second game on top of the memory board: a key you had to find before a lock, a lever');
push('you had to pull before an exit, a shop you had to open, a trap that punished a flip, a decoy that lied about');
push('what a tile was. Every one of those is a **stop**. The loop this game is actually about — flip, match, pop,');
push('ripple, drop, climb, Fever — is a loop of **momentum**, and a stop inside it is a place the player puts the');
push('game down.');
push();
push('The measurements had been saying so for a while without anyone reading them that way:');
push();
push('- The dungeon budget took the floor\'s entire pair count, so the pop had nothing to touch (Gen 167).');
push('- The trim deciding which cards survived a capacity cut needed four passes of protection to stop floors');
push('  losing the card their own archetype was named for (Gen 168).');
push('- Eleven systems in this layer fire on no floor a player ever plays, and have their own standing tasks');
push('  against them (the occupancy census, `sim:occupancy`).');
push();
push('It was expensive, it was fragile, and it was in the way.');
push();
push('## How the removal was staged');
push();
push('It happened in three commits rather than one, because the interesting failure is not "does it still compile"');
push('but "does the game still end":');
push();
push('1. **Gen 171 — one mode.** `GameMode` collapsed to `endless`; daily, puzzle, meditation and gauntlet went,');
push('   with the three balance terms they had quietly been carrying written down in `BALANCE_NOTES.md`.');
push('2. **Gen 172 — generation stops dealing it.** Board generation no longer places a card recipe, a filler pass,');
push('   an exit, a shop, a room, a hazard pass or the layout plan that pinned them. A generated floor is pairs and');
push('   nothing else, asserted over 768 boards in `board-build-rules.test.ts`. This is the commit that matters:');
push('   the modules below still existed and still worked, and the game had already stopped being the game they');
push('   described.');
push('3. **Gen 173 — the modules go.** The files listed at the end are deleted, along with the between-floor layer');
push('   that fed them.');
push();
push('## How to get any of it back');
push();
push('Everything here is in git. The removal commits carry `Gen 171`, `Gen 172` and `Gen 173` in their messages,');
push('and each section names the module a definition lived in, so `git log --all -- src/shared/<module>.ts` finds');
push('its whole history. The intent is not that none of this returns — it is that it returns **deliberately, one');
push('mechanic at a time, measured against the loop** rather than layered on top of it.');
push();
push('## What removing it actually did');
push();
push("Two numbers, both from the repository's own simulations, run immediately before and after the Gen 172 cut:");
push();
push('- **Fever share went from ~0.13 to 0.51 of floors** for a clean player (`yarn sim:cascade`). The dungeon');
push('  budget had been eating the pairs the pop needed to reach, so the cascade could not build. This is the');
push("  thesis's central claim, and it is the first time it has been measured rather than argued.");
push('- **The occupancy census went fully green** (`yarn sim:occupancy`). Eleven systems had been listed as');
push('  silent — shipped and never observable — for eleven generations. They are not quiet now; they are gone,');
push('  which is a different and more honest answer than a widened band.');
push();

push('## Card kinds');
push();
push('From `src/shared/dungeon-cards.ts`. `memoryTax` is what the kind cost the player in things to remember.');
push();
push('| Kind | Family | Rules role | Revealed | Match reward | Mismatch cost | Memory tax | Help text |');
push('|---|---|---|---|---|---|---|---|');
for (const kind of DUNGEON_CARD_KIND_ORDER) {
    const d = DUNGEON_CARD_KIND_DEFINITIONS[kind];
    const tax = calculateMemoryTaxReview(d.memoryTax);
    push(
        `| \`${kind}\` | ${cell(d.familyLabel)} | ${cell(d.rulesRole)} | \`${cell(d.revealTiming)}\` | ` +
            `\`${cell(d.matchReward)}\` | \`${cell(d.mismatchConsequence)}\` | ${tax.total} (${tax.band}) | ${cell(d.helpText)} |`
    );
}
push();
push('### Memory tax by axis');
push();
push('The cost each kind put on the thing the game is actually about — and the finding that matters most in this');
push('whole archive: **every single kind scored `core_safe`.** The taxonomy that was supposed to catch content');
push('taxing the memory game said all eleven kinds were fine. They were, individually. What none of the axes could');
push('see is that eleven individually-cheap stops, stacked, are a different game — and that the cost was never');
push('really to memory, it was to *momentum*, which nothing here measures. That is the lesson worth keeping when');
push('any of this is weighed for return: score the loop, not just the recall.');
push();
push(`| Kind | ${MEMORY_TAX_AXES.join(' | ')} | Total | Band |`);
push(`|---|${MEMORY_TAX_AXES.map(() => '---').join('|')}|---|---|`);
for (const kind of DUNGEON_CARD_KIND_ORDER) {
    const d = DUNGEON_CARD_KIND_DEFINITIONS[kind];
    const tax = calculateMemoryTaxReview(d.memoryTax);
    push(`| \`${kind}\` | ${MEMORY_TAX_AXES.map((axis) => d.memoryTax[axis]).join(' | ')} | ${tax.total} | ${tax.band} |`);
}
push();
push('### What each kind contributed to');
push();
push('| Kind | Objectives it advanced | Mechanic tokens |');
push('|---|---|---|');
for (const kind of DUNGEON_CARD_KIND_ORDER) {
    const d = DUNGEON_CARD_KIND_DEFINITIONS[kind];
    push(`| \`${kind}\` | ${d.objectiveContributions.map((id) => `\`${id}\``).join(', ') || '—'} | ${d.tokens.map((id) => `\`${id}\``).join(', ') || '—'} |`);
}
push();

push('## Card effects');
push();
push('From `src/shared/dungeon-cards.ts`. Each effect is one concrete card a floor could deal.');
push();
push('| Effect | Kind | Label | Rules role | Help text |');
push('|---|---|---|---|---|');
for (const effectId of DUNGEON_CARD_EFFECT_ORDER) {
    const d = DUNGEON_CARD_EFFECT_DEFINITIONS[effectId];
    push(`| \`${effectId}\` | \`${d.kind}\` | ${cell(d.label)} | ${cell(d.rulesRole)} | ${cell(d.helpText)} |`);
}
push();

push('## Bosses');
push();
push('From `src/shared/dungeon-boss-rules.ts`.');
push();
push('| Id | Label | Symbol | HP | Hazard | Pattern | Signature | Reward hook |');
push('|---|---|---|---|---|---|---|---|');
for (const boss of Object.values(DUNGEON_BOSS_DEFINITIONS)) {
    push(
        `| \`${boss.id}\` | ${cell(boss.label)} | \`${cell(boss.symbol)}\` | ${boss.hp} | \`${cell(boss.hazardKind)}\` | ` +
            `\`${cell(boss.hazardPattern)}\` | ${cell(boss.signatureModifier)} | ${cell(boss.rewardHook)} |`
    );
}
push();
push('### Boss card copy');
push();
for (const boss of Object.values(DUNGEON_BOSS_DEFINITIONS)) {
    push(`- **${boss.label}** — ${boss.cardCopy}`);
}
push();

push('## Hazard tiles');
push();
push('From `src/shared/hazard-tiles.ts`. These are the decoys, snares and fake caches - the tiles that lied.');
push();
push('| Kind | Label | Family | Trigger | Outcome | What it told the player |');
push('|---|---|---|---|---|---|');
for (const hazard of Object.values(HAZARD_TILE_DEFINITIONS)) {
    push(
        `| \`${cell(hazard.kind)}\` | ${cell(hazard.label)} | \`${cell(hazard.family)}\` | \`${cell(hazard.trigger)}\` | ` +
            `\`${cell(hazard.outcomeKind)}\` | ${cell(hazard.focusHint)} |`
    );
}
push();
push('### What each hazard did in full');
push();
for (const hazard of Object.values(HAZARD_TILE_DEFINITIONS)) {
    push(`- **${hazard.label}** (\`${hazard.kind}\`)`);
    push(`  - Fires on: ${hazard.triggerScope}`);
    push(`  - Telegraph: ${hazard.telegraph}`);
    push(`  - Outcome: ${hazard.resultCopy}`);
    push(`  - Targeting: ${hazard.targetPolicy}`);
    push(`  - Objective interaction: ${hazard.objectiveInteraction}`);
    push(`  - Enabled in normal runs: ${hazard.enabledInNormalRuns ? 'yes' : 'no'}${hazard.prototypeOnly ? ' (prototype only)' : ''}`);
}
push();

push('## The modules that went with it');
push();
push('Every file below goes in the Gen 173 removal, after Gen 172 had already made all of it unreachable from a');
push('generated floor. `git log --all -- <path>` is its whole history.');
push();
for (const file of DELETED_MODULES) {
    push(`- \`${file}\``);
}
push();

const outPath = path.resolve('docs/REMOVED_DUNGEON_LAYER.md');
fs.writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8');
process.stdout.write(`Wrote ${outPath} (${lines.length} lines)\n`);
