/**
 * Writes docs/REMOVED_DUNGEON_LAYER.md from the live catalogs, before they are deleted.
 *
 * The dungeon layer is being removed because it breaks the flow of the loop this game is actually
 * about. Removed content nobody wrote down is content nobody can weigh returning, so this reads
 * the definitions the game itself holds and prints every kind, effect, boss, hazard, archetype,
 * objective and route special with what it did - accurately, because it is generated from the
 * source rather than remembered.
 *
 * Run: yarn docs:dungeon-archive
 */
import fs from 'node:fs';
import path from 'node:path';
import {
    DUNGEON_CARD_EFFECT_DEFINITIONS,
    DUNGEON_CARD_EFFECT_ORDER,
    DUNGEON_CARD_KIND_DEFINITIONS,
    DUNGEON_CARD_KIND_ORDER
} from '../src/shared/dungeon-cards';
import { DUNGEON_BOSS_DEFINITIONS } from '../src/shared/dungeon-boss-rules';
import { calculateMemoryTaxReview, MEMORY_TAX_AXES } from '../src/shared/mechanic-feedback';
import { HAZARD_TILE_DEFINITIONS } from '../src/shared/hazard-tiles';

/**
 * The modules the removal deletes. Listed here rather than globbed, so the archive still names them
 * accurately after they are gone.
 */
const DELETED_MODULES: readonly string[] = fs
    .readdirSync('src/shared')
    .filter((name) => name.startsWith('dungeon-') && name.endsWith('.ts') && !name.endsWith('.test.ts'))
    .map((name) => `src/shared/${name}`);

const lines: string[] = [];
const push = (line = ''): void => {
    lines.push(line);
};
const cell = (value: unknown): string => String(value ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

push('# The dungeon layer, archived');
push();
push('> Generated by `yarn docs:dungeon-archive` from the catalogs themselves, on the commit before they were');
push('> deleted. Nothing here is remembered or paraphrased: every row is the definition the game shipped.');
push();
push('## Why it was removed');
push();
push('The dungeon layer put a second game on top of the memory board: a key you had to find before a lock, a lever');
push('you had to pull before an exit, a shop you had to open, a trap that punished a flip, a decoy that lied about');
push('what a tile was. Every one of those is a **stop**. The loop this game is actually about — flip, match, pop,');
push('ripple, drop, climb, Fever — is a loop of **momentum**, and a stop inside it is a place the player puts the');
push('game down.');
push();
push('The measurements had been saying so for a while without anyone reading them that way:');
push();
push('- The dungeon budget took the floor\'s entire pair count, so the pop had nothing to touch (Gen 167).');
push('- The trim deciding which cards survived a capacity cut needed four passes of protection to stop floors');
push('  losing the card their own archetype was named for (Gen 168).');
push('- Eleven systems in this layer fire on no floor a player ever plays, and have their own standing tasks');
push('  against them (the occupancy census, `sim:occupancy`).');
push();
push('It was expensive, it was fragile, and it was in the way.');
push();
push('## How to get any of it back');
push();
push('Everything below is in git. The removal commits carry `Gen 171` in the message, and each section names the');
push('module a definition lived in, so `git log --all -- src/shared/<module>.ts` finds its whole history. The intent');
push('is not that none of this returns — it is that it returns **deliberately, one mechanic at a time, measured');
push('against the loop** rather than layered on top of it.');
push();

push('## Card kinds');
push();
push('From `src/shared/dungeon-cards.ts`. `memoryTax` is what the kind cost the player in things to remember.');
push();
push('| Kind | Family | Rules role | Revealed | Match reward | Mismatch cost | Memory tax | Help text |');
push('|---|---|---|---|---|---|---|---|');
for (const kind of DUNGEON_CARD_KIND_ORDER) {
    const d = DUNGEON_CARD_KIND_DEFINITIONS[kind];
    const tax = calculateMemoryTaxReview(d.memoryTax);
    push(
        `| \`${kind}\` | ${cell(d.familyLabel)} | ${cell(d.rulesRole)} | \`${cell(d.revealTiming)}\` | ` +
            `\`${cell(d.matchReward)}\` | \`${cell(d.mismatchConsequence)}\` | ${tax.total} (${tax.band}) | ${cell(d.helpText)} |`
    );
}
push();
push('### Memory tax by axis');
push();
push('The cost each kind put on the thing the game is actually about — and the finding that matters most in this');
push('whole archive: **every single kind scored `core_safe`.** The taxonomy that was supposed to catch content');
push('taxing the memory game said all eleven kinds were fine. They were, individually. What none of the axes could');
push('see is that eleven individually-cheap stops, stacked, are a different game — and that the cost was never');
push('really to memory, it was to *momentum*, which nothing here measures. That is the lesson worth keeping when');
push('any of this is weighed for return: score the loop, not just the recall.');
push();
push(`| Kind | ${MEMORY_TAX_AXES.join(' | ')} | Total | Band |`);
push(`|---|${MEMORY_TAX_AXES.map(() => '---').join('|')}|---|---|`);
for (const kind of DUNGEON_CARD_KIND_ORDER) {
    const d = DUNGEON_CARD_KIND_DEFINITIONS[kind];
    const tax = calculateMemoryTaxReview(d.memoryTax);
    push(`| \`${kind}\` | ${MEMORY_TAX_AXES.map((axis) => d.memoryTax[axis]).join(' | ')} | ${tax.total} | ${tax.band} |`);
}
push();
push('### What each kind contributed to');
push();
push('| Kind | Objectives it advanced | Mechanic tokens |');
push('|---|---|---|');
for (const kind of DUNGEON_CARD_KIND_ORDER) {
    const d = DUNGEON_CARD_KIND_DEFINITIONS[kind];
    push(`| \`${kind}\` | ${d.objectiveContributions.map((id) => `\`${id}\``).join(', ') || '—'} | ${d.tokens.map((id) => `\`${id}\``).join(', ') || '—'} |`);
}
push();

push('## Card effects');
push();
push('From `src/shared/dungeon-cards.ts`. Each effect is one concrete card a floor could deal.');
push();
push('| Effect | Kind | Label | Rules role | Help text |');
push('|---|---|---|---|---|');
for (const effectId of DUNGEON_CARD_EFFECT_ORDER) {
    const d = DUNGEON_CARD_EFFECT_DEFINITIONS[effectId];
    push(`| \`${effectId}\` | \`${d.kind}\` | ${cell(d.label)} | ${cell(d.rulesRole)} | ${cell(d.helpText)} |`);
}
push();

push('## Bosses');
push();
push('From `src/shared/dungeon-boss-rules.ts`.');
push();
push('| Id | Label | Symbol | HP | Hazard | Pattern | Signature | Reward hook |');
push('|---|---|---|---|---|---|---|---|');
for (const boss of Object.values(DUNGEON_BOSS_DEFINITIONS)) {
    push(
        `| \`${boss.id}\` | ${cell(boss.label)} | \`${cell(boss.symbol)}\` | ${boss.hp} | \`${cell(boss.hazardKind)}\` | ` +
            `\`${cell(boss.hazardPattern)}\` | ${cell(boss.signatureModifier)} | ${cell(boss.rewardHook)} |`
    );
}
push();
push('### Boss card copy');
push();
for (const boss of Object.values(DUNGEON_BOSS_DEFINITIONS)) {
    push(`- **${boss.label}** — ${boss.cardCopy}`);
}
push();

push('## Hazard tiles');
push();
push('From `src/shared/hazard-tiles.ts`. These are the decoys, snares and fake caches - the tiles that lied.');
push();
push('| Kind | Label | Family | Trigger | Outcome | What it told the player |');
push('|---|---|---|---|---|---|');
for (const hazard of Object.values(HAZARD_TILE_DEFINITIONS)) {
    push(
        `| \`${cell(hazard.kind)}\` | ${cell(hazard.label)} | \`${cell(hazard.family)}\` | \`${cell(hazard.trigger)}\` | ` +
            `\`${cell(hazard.outcomeKind)}\` | ${cell(hazard.focusHint)} |`
    );
}
push();
push('### What each hazard did in full');
push();
for (const hazard of Object.values(HAZARD_TILE_DEFINITIONS)) {
    push(`- **${hazard.label}** (\`${hazard.kind}\`)`);
    push(`  - Fires on: ${hazard.triggerScope}`);
    push(`  - Telegraph: ${hazard.telegraph}`);
    push(`  - Outcome: ${hazard.resultCopy}`);
    push(`  - Targeting: ${hazard.targetPolicy}`);
    push(`  - Objective interaction: ${hazard.objectiveInteraction}`);
    push(`  - Enabled in normal runs: ${hazard.enabledInNormalRuns ? 'yes' : 'no'}${hazard.prototypeOnly ? ' (prototype only)' : ''}`);
}
push();

push('## The modules that went with it');
push();
push('Every file below was deleted in the Gen 171 removal. `git log --all -- <path>` is its whole history.');
push();
for (const file of DELETED_MODULES) {
    push(`- \`${file}\``);
}
push();

const outPath = path.resolve('docs/REMOVED_DUNGEON_LAYER.md');
fs.writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8');
process.stdout.write(`Wrote ${outPath} (${lines.length} lines)\n`);
